/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


public class AppTest {
    // @Test public void appHasAGreeting() {
    //     ConvolutionMatrix classUnderTest = new ConvolutionMatrix();
    //     assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    // }
}
